# Generated by Django 5.2.3 on 2025-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INITIAL_PURCHASE', 'Initial Purchase'), ('RENEWAL', 'Renewal'), ('CANCELLATION', 'Cancellation'), ('UNCANCELLATION', 'Uncancellation'), ('EXPIRATION', 'Expiration'), ('BILLING_ISSUE', 'Billing Issue'), ('PRODUCT_CHANGE', 'Product Change'), ('SUBSCRIPTION_PAUSED', 'Subscription Paused'), ('SUBSCRIPTION_RESUMED', 'Subscription Resumed')], max_length=50)),
                ('app_user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('product_id', models.CharField(blank=True, max_length=200, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
