# Generated by Django 5.2.3 on 2025-09-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0010_remove_otp_email_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
