# Generated by Django 5.2.3 on 2025-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0011_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
