# Generated by Django 5.2.3 on 2025-09-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='vapi_phone_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
