# Generated by Django 5.2.3 on 2025-09-16 10:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0005_hoursofoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_types', multiselectfield.db.fields.MultiSelectField(choices=[('client_inquiries', 'Client Inquiries'), ('bookings', 'Bookings'), ('support', 'Support'), ('sales', 'Sales'), ('follow_up', 'Follow-up'), ('personalized', 'Personalized'), ('mixed', 'Mixed')], max_length=100)),
                ('industries', multiselectfield.db.fields.MultiSelectField(choices=[('real_estate', 'Real Estate'), ('business_development', 'Business Development'), ('technology', 'Technology'), ('operation', 'Operation'), ('accounting', 'Accounting'), ('recruiting', 'Recruiting'), ('sales', 'Sales'), ('others', 'Others')], max_length=100)),
                ('work_styles', multiselectfield.db.fields.MultiSelectField(choices=[('solo', 'Solo'), ('small_team', 'Small Team'), ('growing_business', 'Growing Business'), ('remote', 'Remote'), ('freelancer', 'Freelancer'), ('on_site', 'On-Site'), ('others', 'Others')], max_length=100)),
                ('assistances', multiselectfield.db.fields.MultiSelectField(choices=[('answer_calls', 'Answer Calls'), ('share_info', 'Share Info'), ('handle_bookings', 'Handle Bookings'), ('schedule_meetings', 'Schedule Meetings'), ('faqs', 'FAQs'), ('collect_leads', 'Collect Leads'), ('others', 'Others')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
