# Generated by Django 5.2.3 on 2025-09-16 12:06

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0006_calldata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='assistances',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Answer Calls', 'Answer Calls'), ('Share Info', 'Share Info'), ('Handle Bookings', 'Handle Bookings'), ('Schedule Meetings', 'Schedule Meetings'), ('FAQs', 'FAQs'), ('Collect Leads', 'Collect Leads'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='call_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Client Inquiries', 'Client Inquiries'), ('Bookings', 'Bookings'), ('Support', 'Support'), ('Sales', 'Sales'), ('Follow-up', 'Follow-up'), ('Personalized', 'Personalized'), ('Mixed', 'Mixed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='industries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Real Estate', 'Real Estate'), ('Business Development', 'Business Development'), ('Technology', 'Technology'), ('Operation', 'Operation'), ('Accounting', 'Accounting'), ('Recruiting', 'Recruiting'), ('Sales', 'Sales'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='work_styles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Solo', 'Solo'), ('Small Team', 'Small Team'), ('Growing Business', 'Growing Business'), ('Remote', 'Remote'), ('Freelancer', 'Freelancer'), ('On-Site', 'On-Site'), ('Others', 'Others')], max_length=100),
        ),
    ]
