# Generated by Django 5.2.3 on 2025-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0007_calldata_user_alter_calldata_assistances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglink',
            name='booking_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
