# Generated by Django 5.2.3 on 2025-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0009_prioritycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='vapi_assistant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
