# Generated by Django 5.2.3 on 2025-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0010_alter_aiassistant_vapi_assistant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursofoperation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
