# Generated by Django 5.2.3 on 2025-10-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0011_hoursofoperation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='ring',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
