# Generated by Django 5.2.3 on 2025-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0012_aiassistant_ring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='voice_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
