# Generated by Django 5.2.3 on 2025-10-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_call', '0013_alter_aiassistant_voice_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='ring',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
